id: 82fd6d077df141628cd7f638b57c70c5
initial_creation_type: ebook
created_at: 21/05/2021
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །དགེ་སློང་གི་བསླབ་བྱ་གནམ་རྩེང་ལྡེང་མར་གྲགས་པ་བཞུགས་སོ།།
  subtitle: ''
  authors:
  - ' རྗེ་ཙོང་ཁ་པ་བློ་བཟང་གྲགས་པ།'
  collection: Tsadra Geluk Series
  publisher: Tsadra Publishing
  id: TSD-GS-03
  cover: tmprx2k5ug0.jpg
  credit: tmpo4ota3q6.jpg
